### ISSUE TITLE
compile error in angular 8

### ISSUE THREAD

**Issue by WKielen** [fundsaccess/angular-iban#3]
After upgrading my project from Angular 6 to Angular 8, this library gave an compile error:

ERROR in ./node_modules/angular-iban/fesm2015/angular-iban.js
Module not found: Error: Can't resolve 'iban' in 'xxx\node_modules\angular-iban\fesm2015'
i ｢wdm｣: Failed to compile.

**Comment by kimljj** [comment]
Hello @WKielen ,
Is it sitll a problem? I just tried angular(8.2.14) and angular-iban(0.1.6), i didn't have any problems. Could you pls retry?

**Comment by WKielen** [comment]
I was using version 0.2.0 when the error occured. After installing 0.1.6 I recompiled and unfortunately I got the same error.

Angular CLI: 8.3.20
Node: 10.16.0
OS: win32 x64
Angular: 8.2.14

**Comment by WKielen** [comment]
For some reason the dependency on "iban": "0.0.12"  was not installed. After installing this library manually, it worked fine. Thanks.
