### ISSUE TITLE
Upgrade for angular 9

### ISSUE THREAD

**Issue by frontendplace** [fundsaccess/angular-iban#6]
Is there a change to upgrade this to a angular 9 supporting version?

**Comment by fundsaccess** [comment]
Hi @frontendplace,

do you have some problems? I just did some tests regarding you comment on angular 9.1.7. angular-iban is still working. 

Kind regards,
fundsaccess F/E team

**Comment by Braincompiler** [comment]
The command `ng update @angular/core @angular/cli` leads to:

![image](https://user-images.githubusercontent.com/142524/84405906-1417ab00-ac09-11ea-8b39-7ce079810a03.png)

**Comment by fundsaccess** [comment]
@Braincompiler,
thank a lot for the information. 

Hi @all,
This library was updated to support Angular9 migration. Please check if it would solve your problem.

Sorry for the inconvenience and hope all of you have a good week!

fundsaccess F/E team

**Comment by fundsaccess** [comment]
Since two weeks no further problems regarding this issue.
